### HELP
GET http://localhost:3001/info

### GET ALL
GET http://localhost:3001/api/persons

### GET FOR ID
GET http://localhost:3001/api/persons/67e034be029ca03e46a5c565

### DELETE FOR ID
DELETE http://localhost:3001/api/persons/67e0af039a44fb4732778305

### SAVE NEW NOTE
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "dam",
    "phone": 7
}

### UPDATE OLD NOTE
PUT http://localhost:3001/api/persons/67e03d440c895ae9e7fb0473
Content-Type: application/json

{
    "name": "An",
    "phone": 5
}
